# Generated by Django 3.0.7 on 2020-06-23 18:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20200617_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='subTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=250)),
                ('completed', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=0, null=True)),
                ('author_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.todoItem')),
            ],
        ),
    ]
