# Generated by Django 3.0.7 on 2020-06-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_subtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subTask',
        ),
    ]
